apiVersion: v1
kind: Service
metadata:
  name: java-hello-service
spec:
  selector:
    app: java-hello
  type: ClusterIP
  ports:
  - name: java-hello-service
    port: 80
    targetPort: 3000
    protocol: TCP
